---
name: Ruby Tests

on:
  pull_request:
  push:
    branches:
      - main
      - '*-stable'

concurrency:
  group: ${{ github.ref_name }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  setup-dependencies:
    name: Install system dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Install libcurl and libxml2
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev libxml2-dev

  rubocop:
    uses: theforeman/actions/.github/workflows/rubocop.yml@v0
    with:
      command: bundle exec rubocop --parallel --format github
      ruby: '3.0'

  test:
    name: Ruby
    needs:
      - rubocop
      - setup-dependencies
    uses: theforeman/actions/.github/workflows/foreman_plugin.yml@v0
    with:
      plugin: foreman_ovirt